import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'RU' | 'EN' | 'AR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  RU: {
    // Nav
    // Site / Auth
    'site.name': 'Мирный призыв',
    'auth.backHome': 'На главную',
    'auth.tagline': 'Присоединяйтесь к сообществу',
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.faq': 'Вопросы',
    'nav.contact': 'Контакт',
    'nav.signin': 'Войти',
    'nav.signup': 'Регистрация',
    'nav.admin': 'Управление',
    'nav.signout': 'Выйти',
    'nav.manageAccount': 'Мой аккаунт',
    'nav.posts': 'Статьи',
    'nav.donate': 'Пожертвование',
    // Hero
    'hero.eyebrow': 'Путь к Истине',
    'hero.headline': 'От сомнений к истине',
    'hero.question': 'Как найти подлинное спокойствие и вечное счастье?',
    'hero.invite': 'Мы приглашаем вас к единобожию — пути, дарующему свет и ясность.',
    // Pills
    'pill.meaning': 'Смысл жизни',
    'pill.happiness': 'Истинное счастье',
    'pill.peace': 'Внутренний покой',
    'pill.purpose': 'Предназначение',
    'pill.hope': 'Надежда',
    'pill.mercy': 'Милость',
    // Verses
    'verses.title': 'Мы нашли ответ — в Исламе',
    'verses.1.quote': 'И несомненно, в поминании Бога сердца обретают утешение.',
    'verses.1.cite': 'Коран 13:28',
    'verses.2.quote': 'Тот, кто совершает добро и искренне верит, тому Мы даруем благую жизнь.',
    'verses.2.cite': 'Коран 16:97',
    'verses.3.quote': 'Не отчаивайтесь в милости Бога. Поистине, Он прощает все грехи тем, кто обращается к Нему.',
    'verses.3.cite': 'Коран 39:53',
    'verses.4.quote': 'Мы ниспосылаем в Коране то, что является исцелением и милостью для верующих.',
    'verses.4.cite': 'Коран 17:82',
    // About
    'about.title': 'О нас',
    'about.desc': 'Peaceful Call — это пространство уважительного диалога и честных размышлений. Мы ведем спокойные, аргументированные беседы о вере и истине с христианами, атеистами и представителями других взглядов. Наша цель — не победить в споре, а пригласить к истине через разум и доказательства.',
    'about.bullet.1': 'Сравнительная религия',
    'about.bullet.2': 'Ответы на сложные вопросы о вере',
    'about.bullet.3': 'Уважительные дискуссии',
    'about.bullet.4': 'Поиск смысла жизни',
    'about.closing': 'Одна истина. Один путь. Один мирный призыв.',
    // Support
    'support.title': 'Поддержите проект',
    'support.text': 'Помогите нам продолжать это дело. Поддержка благого дела несет в себе награду.',
    'support.button': 'Пожертвовать',
    'support.accepted': 'Да примется ваша поддержка',
    // Stats
    'stats.views': 'Просмотров',
    'stats.videos': 'Видео',
    'stats.hours': 'Часов эфира',
    'stats.faith': 'Обрели веру',
    // FAQ
    'faq.title': 'Частые вопросы',
    'faq.q1': 'В чем смысл моей жизни?',
    'faq.a1': 'Смысл жизни заключается в познании своего Создателя и искреннем служении Ему. Когда мы выстраиваем связь с Богом, жизнь обретает глубокое значение, а наши поступки наполняются светом.',
    'faq.q2': 'Почему я не чувствую истинного счастья?',
    'faq.a2': 'Настоящее счастье не измеряется материальными благами или временными удовольствиями. Душа, созданная Богом, нуждается в Нем так же, как тело нуждается в пище.',
    'faq.q3': 'Почему в мире так много боли и несправедливости?',
    'faq.a3': 'Этот мир — не место абсолютного совершенства, а временная обитель испытаний. Справедливость восторжествует в вечности.',
    'faq.q4': 'Что происходит после смерти?',
    'faq.a4': 'Смерть — это не конец, а переход в новую, вечную жизнь. Каждая душа вернется к своему Создателю, чтобы получить справедливое воздаяние.',
    'faq.q5': 'Сможет ли Бог простить меня?',
    'faq.a5': 'Двери Божьей милости всегда открыты для тех, кто искренне раскаивается. Нет такого греха, который был бы больше милосердия Творца.',
    'faq.q6': 'Как обрести мир в душе?',
    'faq.a6': 'Мир в душе приходит, когда человек примиряется со своим Создателем и следует Его руководству.',
    // Contact
    'contact.title': 'Остались вопросы?',
    'contact.text': 'Мы всегда открыты для диалога. Напишите нам, чтобы обсудить то, что вас волнует.',
    'contact.button': 'Начать беседу',
    // Footer
    'footer.tagline': 'Приглашение к истине через разум и доказательства.',
    'footer.copy': '© 2024 Peaceful Call. Все права защищены.',
    // Posts page
    'posts.title': 'Статьи',
    'posts.subtitle': 'Размышления, ответы и истины от команды Peaceful Call',
    'posts.readMore': 'Читать далее',
    'posts.back': 'Назад',
    'posts.noArticles': 'Статей пока нет. Следите за обновлениями.',
    'posts.by': 'Автор',
    // Comments & reactions
    'post.comments': 'Комментарии',
    'post.noComments': 'Пока нет комментариев. Оставьте первый!',
    'post.addComment': 'Написать комментарий...',
    'post.send': 'Отправить',
    'post.signInToComment': 'Войдите, чтобы оставить комментарий',
    'post.signIn': 'Войти',
    'post.likes': 'Нравится',
    'post.dislikes': 'Не нравится',
    'post.admin': 'Админ',
    'post.deleteComment': 'Удалить',
    // Portal
    'portal.greeting': 'Добро пожаловать',
    'portal.subtitle': 'Здесь вы можете общаться, управлять настройками и находить ответы.',
    'portal.messages': 'Сообщения',
    'portal.messagesDesc': 'Свяжитесь с администрацией или другими участниками.',
    'portal.team': 'Команда',
    'portal.teamDesc': 'Познакомьтесь с теми, кто поддерживает Peaceful Call.',
    'portal.settings': 'Настройки',
    'portal.settingsDesc': 'Управляйте своим профилем и аккаунтом.',
    'portal.admin': 'Панель управления',
    'portal.adminDesc': 'Управление контентом, публикациями и настройками.',
    'portal.openChat': 'Открыть чат',
    'portal.goto': 'Перейти',
    'portal.open': 'Открыть',
    'portal.manage': 'Управление',
    // Admins panel
    'admins.team': 'Команда проекта',
    'admins.teamDesc': 'Познакомьтесь с теми, кто стоит за Peaceful Call.',
    'admins.founder': 'Основатель',
    'admins.admin': 'Администратор',
    'admins.writeMessage': 'Написать сообщение',
    // Admin panel
    'admin.panel': 'Панель управления',
    'admin.signInRequired': 'Войдите в аккаунт, чтобы продолжить',
    'admin.signIn': 'Войти',
    'admin.accessDenied': 'Доступ ограничён',
    'admin.accessDeniedDesc': 'Ваш аккаунт не зарегистрирован как администратор. Обратитесь к владельцу сайта.',
    'admin.signOut': 'Выйти',
    'admin.content': 'Контент',
    'admin.posts': 'Публикации',
    'admin.messages': 'Сообщения',
    'admin.admins': 'Администраторы',
    'admin.users': 'Пользователи',
    'admin.newPost': 'Новая публикация',
    'admin.transferOwner': 'Передать права владельца',
    'admin.makeAdmin': 'Назначить администратором',
    'admin.save': 'Сохранить',
    'admin.cancel': 'Отмена',
    'admin.delete': 'Удалить',
    'admin.edit': 'Редактировать',
    'admin.back': 'Назад',
    'admin.published': 'Опубликовано',
    'admin.draft': 'Черновик',
    'admin.title': 'Заголовок',
    'admin.excerpt': 'Краткое описание',
    'admin.coverUrl': 'Ссылка на обложку',
    'admin.content_text': 'Содержание',
    'admin.attachments': 'Вложения',
    'admin.addFiles': 'Добавить файлы',
    'admin.uploading': 'Загрузка...',
    'post.attachments': 'Материалы',
    'post.download': 'Скачать',
    'admin.addNew': 'Добавить',
    'admin.noItems': 'Элементов пока нет',
    'admin.inbox': 'Входящие',
    'admin.noMessages': 'Сообщений пока нет',
    'admin.selectMsg': 'Выберите сообщение для просмотра',
    'admin.reply': 'Ответить',
    'admin.replyPlaceholder': 'Напишите ответ...',
    'admin.sendReply': 'Отправить ответ',
    'admin.noSubject': 'Без темы',
    'admin.from': 'От',
    'admin.youOwner': 'Вы — главный администратор.',
    'admin.ownerDesc': 'Вы можете назначать других пользователей администраторами и передавать права.',
    'admin.inviteAdmin': 'Добавить администратора',
    'admin.inviteEmail': 'Email пользователя',
    'admin.inviteRole': 'Роль',
    'admin.roleEditor': 'Редактор',
    'admin.roleOwner': 'Владелец',
    'admin.invite': 'Добавить',
    'admin.banUser': 'Заблокировать',
    'admin.unbanUser': 'Разблокировать',
    'admin.muteUser': 'Заглушить',
    'admin.unmuteUser': 'Снять глушение',
    'admin.deleteUser': 'Удалить пользователя',
    'admin.banned': 'Заблокирован',
    'admin.muted': 'Заглушен',
    'admin.active': 'Активен',
    'admin.noUsers': 'Пользователи не найдены',
    'admin.userMgmt': 'Управление пользователями',
    'admin.userMgmtDesc': 'Блокировка, глушение и удаление пользователей',
    'admin.confirmBan': 'Заблокировать этого пользователя?',
    'admin.confirmDelete': 'Удалить этого пользователя? Это действие нельзя отменить.',
    'admin.fieldKey': 'Поле',
    'admin.fieldValue': 'Значение',
    'admin.fieldGroup': 'Раздел',
    'admin.fieldType': 'Тип',
    'admin.contentMgmt': 'Управление контентом',
    'admin.contentDesc': 'Измените тексты, изображения и ссылки на сайте',
    // Messages
    'messages.title': 'Сообщения',
    'messages.subtitle': 'Ваши беседы с администрацией и участниками',
    'messages.newConv': 'Новая беседа',
    'messages.noConvs': 'У вас пока нет активных диалогов',
    'messages.search': 'Поиск бесед...',
    'messages.admin': 'Администрация',
    'messages.noMessages': 'Нет сообщений',
    'messages.selectConv': 'Выберите беседу для начала общения',
    'messages.send': 'Отправить',
    'messages.type': 'Написать сообщение...',
    'messages.newDialog': 'Начать диалог',
    'messages.support': 'Служба поддержки / Администрация',
    'messages.supportDesc': 'Задать вопрос команде сайта',
    'messages.or': 'Или с участником',
    'messages.searchUser': 'Поиск по имени...',
    'messages.noUsers': 'Пользователи не найдены',
    // Hadiths
    'nav.hadiths': 'Хадисы',
    'hadiths.title': 'Хадисы',
    'hadiths.subtitle': 'Изречения Пророка ﷺ с указанием степени достоверности',
    'hadiths.all': 'Все',
    'hadiths.none': 'Хадисов пока нет.',
    'hadiths.narrator': 'Передатчик',
    'hadiths.source': 'Источник',
    'admin.hadiths': 'Хадисы',
    'admin.newHadith': 'Новый хадис',
    'admin.hadithText': 'Текст хадиса',
    'admin.hadithSource': 'Источник (сборник, номер)',
    'admin.hadithNarrator': 'Передатчик',
    'admin.hadithTopic': 'Тема',
    'admin.hadithGrade': 'Степень достоверности',
    'admin.gradeSahih': 'Достоверный (сахих)',
    'admin.gradeHasan': 'Хороший (хасан)',
    'admin.gradeDaif': 'Слабый (даиф)',
    'admin.gradeMawdu': 'Вымышленный (мавду)',
  },
  EN: {
    // Nav
    // Site / Auth
    'site.name': 'Peaceful Call',
    'auth.backHome': 'Back to home',
    'auth.tagline': 'Join the community',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.signin': 'Sign In',
    'nav.signup': 'Sign Up',
    'nav.admin': 'Dashboard',
    'nav.signout': 'Sign Out',
    'nav.manageAccount': 'My Account',
    'nav.posts': 'Articles',
    'nav.donate': 'Donate',
    // Hero
    'hero.eyebrow': 'The Path to Truth',
    'hero.headline': 'From confusion to truth',
    'hero.question': 'How can one find true contentment and lasting happiness?',
    'hero.invite': 'We invite you toward monotheism — a path of light and clarity.',
    // Pills
    'pill.meaning': 'Meaning of life',
    'pill.happiness': 'True happiness',
    'pill.peace': 'Inner peace',
    'pill.purpose': 'True purpose',
    'pill.hope': 'Hope',
    'pill.mercy': 'Mercy',
    // Verses
    'verses.title': 'We found the answer — in Islam',
    'verses.1.quote': 'Verily, in the remembrance of God do hearts find rest.',
    'verses.1.cite': 'Quran 13:28',
    'verses.2.quote': 'Whoever does righteousness and believes, We will surely grant them a good life.',
    'verses.2.cite': 'Quran 16:97',
    'verses.3.quote': 'Do not despair of the mercy of God. Indeed, He forgives all sins for those who turn to Him.',
    'verses.3.cite': 'Quran 39:53',
    'verses.4.quote': 'We send down in the Quran that which is a healing and a mercy for the believers.',
    'verses.4.cite': 'Quran 17:82',
    // About
    'about.title': 'About us',
    'about.desc': 'Peaceful Call is a space for respectful dialogue and honest reflection. We host calm, well-reasoned conversations about faith and truth with Christians, atheists, and others. Our goal is not to win arguments, but to invite people toward truth through reason and evidence.',
    'about.bullet.1': 'Comparative religion',
    'about.bullet.2': 'Answers to complex questions about faith',
    'about.bullet.3': 'Respectful debates',
    'about.bullet.4': 'Reasoning about the meaning of life',
    'about.closing': 'One truth. One path. One peaceful call.',
    // Support
    'support.title': 'Support our project',
    'support.text': 'Help us continue this mission. Supporting good work carries its own reward.',
    'support.button': 'Donate Now',
    'support.accepted': 'May your support be accepted',
    // Stats
    'stats.views': 'Views',
    'stats.videos': 'Videos',
    'stats.hours': 'Hours of livestreams',
    'stats.faith': 'Found faith',
    // FAQ
    'faq.title': 'Common Questions',
    'faq.q1': 'What is the meaning of my life?',
    'faq.a1': 'The meaning of life is to know our Creator and sincerely serve Him. When we build a connection with God, life gains profound significance.',
    'faq.q2': "Why don't I feel true happiness?",
    'faq.a2': "True happiness is not measured by material wealth or temporary pleasures. The soul, created by God, needs Him just as the body needs food.",
    'faq.q3': 'Why is there so much pain and injustice in the world?',
    'faq.a3': 'This world is not a place of absolute perfection, but a temporary abode of trials. Justice will prevail in eternity.',
    'faq.q4': 'What happens after death?',
    'faq.a4': 'Death is not the end, but a transition to a new, eternal life. Every soul will return to its Creator to receive fair recompense.',
    'faq.q5': 'Can God forgive me?',
    'faq.a5': "The doors of God's mercy are always open to those who sincerely repent. There is no sin greater than the mercy of the Creator.",
    'faq.q6': 'How do I find peace within?',
    'faq.a6': "Inner peace comes when a person reconciles with their Creator and follows His guidance.",
    // Contact
    'contact.title': 'Still have questions?',
    'contact.text': 'We are always open to dialogue. Reach out to discuss what is on your mind.',
    'contact.button': 'Start a conversation',
    // Footer
    'footer.tagline': 'An invitation to truth through reason and evidence.',
    'footer.copy': '© 2024 Peaceful Call. All rights reserved.',
    // Posts
    'posts.title': 'Articles',
    'posts.subtitle': 'Reflections, answers, and truths from the Peaceful Call team',
    'posts.readMore': 'Read more',
    'posts.back': 'Back',
    'posts.noArticles': 'No articles yet. Check back soon.',
    'posts.by': 'By',
    // Comments
    'post.comments': 'Comments',
    'post.noComments': 'No comments yet. Be the first!',
    'post.addComment': 'Write a comment...',
    'post.send': 'Send',
    'post.signInToComment': 'Sign in to leave a comment',
    'post.signIn': 'Sign In',
    'post.likes': 'Like',
    'post.dislikes': 'Dislike',
    'post.admin': 'Admin',
    'post.deleteComment': 'Delete',
    // Portal
    'portal.greeting': 'Welcome',
    'portal.subtitle': 'Here you can communicate, manage settings, and find answers.',
    'portal.messages': 'Messages',
    'portal.messagesDesc': 'Contact the administration or other members.',
    'portal.team': 'Team',
    'portal.teamDesc': 'Meet the people behind Peaceful Call.',
    'portal.settings': 'Settings',
    'portal.settingsDesc': 'Manage your profile and account.',
    'portal.admin': 'Admin Panel',
    'portal.adminDesc': 'Manage content, publications, and settings.',
    'portal.openChat': 'Open Chat',
    'portal.goto': 'Go',
    'portal.open': 'Open',
    'portal.manage': 'Manage',
    // Admins
    'admins.team': 'Project Team',
    'admins.teamDesc': 'Meet the people behind Peaceful Call.',
    'admins.founder': 'Founder',
    'admins.admin': 'Administrator',
    'admins.writeMessage': 'Send a message',
    // Admin panel
    'admin.panel': 'Admin Panel',
    'admin.signInRequired': 'Please sign in to continue.',
    'admin.signIn': 'Sign In',
    'admin.accessDenied': 'Access Denied',
    'admin.accessDeniedDesc': 'Your account is not registered as an administrator. Contact the site owner.',
    'admin.signOut': 'Sign Out',
    'admin.content': 'Content',
    'admin.posts': 'Posts',
    'admin.messages': 'Messages',
    'admin.admins': 'Admins',
    'admin.users': 'Users',
    'admin.newPost': 'New Post',
    'admin.transferOwner': 'Transfer Ownership',
    'admin.makeAdmin': 'Make Admin',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.edit': 'Edit',
    'admin.back': 'Back',
    'admin.published': 'Published',
    'admin.draft': 'Draft',
    'admin.title': 'Title',
    'admin.excerpt': 'Excerpt',
    'admin.coverUrl': 'Cover Image URL',
    'admin.content_text': 'Content',
    'admin.attachments': 'Attachments',
    'admin.addFiles': 'Add files',
    'admin.uploading': 'Uploading...',
    'post.attachments': 'Attachments',
    'post.download': 'Download',
    'admin.addNew': 'Add',
    'admin.noItems': 'No items yet',
    'admin.inbox': 'Inbox',
    'admin.noMessages': 'No messages yet',
    'admin.selectMsg': 'Select a message to view',
    'admin.reply': 'Reply',
    'admin.replyPlaceholder': 'Write a reply...',
    'admin.sendReply': 'Send Reply',
    'admin.noSubject': 'No subject',
    'admin.from': 'From',
    'admin.youOwner': 'You are the owner admin.',
    'admin.ownerDesc': 'You can assign other users as administrators and transfer ownership.',
    'admin.inviteAdmin': 'Add Administrator',
    'admin.inviteEmail': "User's email",
    'admin.inviteRole': 'Role',
    'admin.roleEditor': 'Editor',
    'admin.roleOwner': 'Owner',
    'admin.invite': 'Add',
    'admin.banUser': 'Ban',
    'admin.unbanUser': 'Unban',
    'admin.muteUser': 'Mute',
    'admin.unmuteUser': 'Unmute',
    'admin.deleteUser': 'Delete User',
    'admin.banned': 'Banned',
    'admin.muted': 'Muted',
    'admin.active': 'Active',
    'admin.noUsers': 'No users found',
    'admin.userMgmt': 'User Management',
    'admin.userMgmtDesc': 'Ban, mute, and delete users',
    'admin.confirmBan': 'Ban this user?',
    'admin.confirmDelete': 'Delete this user? This cannot be undone.',
    'admin.fieldKey': 'Field',
    'admin.fieldValue': 'Value',
    'admin.fieldGroup': 'Group',
    'admin.fieldType': 'Type',
    'admin.contentMgmt': 'Content Management',
    'admin.contentDesc': 'Edit texts, images, and links on the site',
    // Messages
    'messages.title': 'Messages',
    'messages.subtitle': 'Your conversations with the team and community members',
    'messages.newConv': 'New Conversation',
    'messages.noConvs': 'No active conversations yet',
    'messages.search': 'Search conversations...',
    'messages.admin': 'Administration',
    'messages.noMessages': 'No messages',
    'messages.selectConv': 'Select a conversation to start chatting',
    'messages.send': 'Send',
    'messages.type': 'Write a message...',
    'messages.newDialog': 'Start a dialog',
    'messages.support': 'Support / Administration',
    'messages.supportDesc': 'Ask the site team a question',
    'messages.or': 'Or with a member',
    'messages.searchUser': 'Search by name...',
    'messages.noUsers': 'No users found',
    // Hadiths
    'nav.hadiths': 'Hadiths',
    'hadiths.title': 'Hadiths',
    'hadiths.subtitle': 'Sayings of the Prophet \u25cb with authenticity grading',
    'hadiths.all': 'All',
    'hadiths.none': 'No hadiths yet.',
    'hadiths.narrator': 'Narrator',
    'hadiths.source': 'Source',
    'admin.hadiths': 'Hadiths',
    'admin.newHadith': 'New Hadith',
    'admin.hadithText': 'Hadith text',
    'admin.hadithSource': 'Source (collection, number)',
    'admin.hadithNarrator': 'Narrator',
    'admin.hadithTopic': 'Topic',
    'admin.hadithGrade': 'Authenticity grade',
    'admin.gradeSahih': 'Authentic (Sahih)',
    'admin.gradeHasan': 'Good (Hasan)',
    'admin.gradeDaif': 'Weak (Da\u2019if)',
    'admin.gradeMawdu': 'Fabricated (Mawdu\u2019)',
  },
  AR: {
    // Nav
    // Site / Auth
    'site.name': 'الدعوة السلمية',
    'auth.backHome': 'العودة إلى الرئيسية',
    'auth.tagline': 'انضم إلى المجتمع',
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.contact': 'اتصل بنا',
    'nav.signin': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.admin': 'لوحة الإدارة',
    'nav.signout': 'تسجيل الخروج',
    'nav.manageAccount': 'حسابي',
    'nav.posts': 'المقالات',
    'nav.donate': 'تبرع',
    // Hero
    'hero.eyebrow': 'الطريق إلى الحقيقة',
    'hero.headline': 'من الحيرة إلى اليقين',
    'hero.question': 'كيف يمكن للمرء أن يجد الرضا الحقيقي والسعادة الدائمة؟',
    'hero.invite': 'ندعوكم إلى التوحيد — طريق يمنح النور والوضوح.',
    // Pills
    'pill.meaning': 'معنى الحياة',
    'pill.happiness': 'السعادة الحقيقية',
    'pill.peace': 'السلام الداخلي',
    'pill.purpose': 'الغاية الحقيقية',
    'pill.hope': 'الأمل',
    'pill.mercy': 'الرحمة',
    // Verses
    'verses.title': 'لقد وجدنا الإجابة — في الإسلام',
    'verses.1.quote': 'ألا بذكر الله تطمئن القلوب.',
    'verses.1.cite': 'القرآن ١٣:٢٨',
    'verses.2.quote': 'من عمل صالحا من ذكر أو أنثى وهو مؤمن فلنحيينه حياة طيبة.',
    'verses.2.cite': 'القرآن ١٦:٩٧',
    'verses.3.quote': 'لا تقنطوا من رحمة الله إن الله يغفر الذنوب جميعا.',
    'verses.3.cite': 'القرآن ٣٩:٥٣',
    'verses.4.quote': 'وننزل من القرآن ما هو شفاء ورحمة للمؤمنين.',
    'verses.4.cite': 'القرآن ١٧:٨٢',
    // About
    'about.title': 'من نحن',
    'about.desc': 'نداء السلام هو مساحة للحوار المحترم والتأمل الصادق. نجري محادثات هادئة ومنطقية حول الإيمان والحقيقة مع المسيحيين والملحدين وغيرهم. هدفنا ليس الفوز في الجدال، بل الدعوة إلى الحقيقة بالعقل والأدلة.',
    'about.bullet.1': 'مقارنة الأديان',
    'about.bullet.2': 'إجابات على الأسئلة المعقدة حول الإيمان',
    'about.bullet.3': 'مناقشات محترمة',
    'about.bullet.4': 'البحث في معنى الحياة',
    'about.closing': 'حقيقة واحدة. طريق واحد. نداء سلام واحد.',
    // Support
    'support.title': 'ادعم مشروعنا',
    'support.text': 'ساعدنا في مواصلة هذه المهمة. دعم العمل الصالح يحمل في طياته أجره.',
    'support.button': 'تبرع الآن',
    'support.accepted': 'تقبّل الله تبرعكم',
    // Stats
    'stats.views': 'مشاهدات',
    'stats.videos': 'مقاطع فيديو',
    'stats.hours': 'ساعات بث مباشر',
    'stats.faith': 'وجدوا الإيمان',
    // FAQ
    'faq.title': 'الأسئلة الشائعة',
    'faq.q1': 'ما هو معنى حياتي؟',
    'faq.a1': 'معنى الحياة هو معرفة خالقنا وعبادته بصدق. عندما نبني صلة بالله، تكتسب الحياة أهمية عميقة.',
    'faq.q2': 'لماذا لا أشعر بالسعادة الحقيقية؟',
    'faq.a2': 'لا تُقاس السعادة الحقيقية بالثروة المادية أو المتع المؤقتة. الروح التي خلقها الله تحتاجه كما يحتاج الجسد إلى الطعام.',
    'faq.q3': 'لماذا يوجد الكثير من الألم والظلم في العالم؟',
    'faq.a3': 'هذا العالم ليس دار كمال مطلق، بل دار ابتلاء مؤقتة. العدالة ستسود في الآخرة.',
    'faq.q4': 'ماذا يحدث بعد الموت؟',
    'faq.a4': 'الموت ليس النهاية، بل انتقال إلى حياة جديدة أبدية. كل روح ستعود إلى خالقها لتنال جزاءها العادل.',
    'faq.q5': 'هل يمكن لله أن يغفر لي؟',
    'faq.a5': 'أبواب رحمة الله مفتوحة دائماً لأولئك الذين يتوبون بصدق. لا يوجد ذنب أعظم من رحمة الخالق.',
    'faq.q6': 'كيف أجد السلام الداخلي؟',
    'faq.a6': 'السلام الداخلي يأتي عندما يتصالح الإنسان مع خالقه ويتبع هداه.',
    // Contact
    'contact.title': 'هل لا يزال لديك أسئلة؟',
    'contact.text': 'نحن منفتحون دائماً للحوار. تواصل معنا لمناقشة ما يشغل تفكيرك.',
    'contact.button': 'ابدأ المحادثة',
    // Footer
    'footer.tagline': 'دعوة إلى الحقيقة من خلال العقل والأدلة.',
    'footer.copy': '© 2024 نداء السلام. جميع الحقوق محفوظة.',
    // Posts
    'posts.title': 'المقالات',
    'posts.subtitle': 'تأملات وإجابات وحقائق من فريق نداء السلام',
    'posts.readMore': 'قراءة المزيد',
    'posts.back': 'رجوع',
    'posts.noArticles': 'لا توجد مقالات بعد. تابعنا للمزيد.',
    'posts.by': 'بقلم',
    // Comments
    'post.comments': 'التعليقات',
    'post.noComments': 'لا توجد تعليقات بعد. كن الأول!',
    'post.addComment': 'اكتب تعليقاً...',
    'post.send': 'إرسال',
    'post.signInToComment': 'سجّل الدخول لترك تعليق',
    'post.signIn': 'تسجيل الدخول',
    'post.likes': 'إعجاب',
    'post.dislikes': 'عدم إعجاب',
    'post.admin': 'مشرف',
    'post.deleteComment': 'حذف',
    // Portal
    'portal.greeting': 'مرحباً بك',
    'portal.subtitle': 'يمكنك هنا التواصل وإدارة الإعدادات والعثور على إجابات.',
    'portal.messages': 'الرسائل',
    'portal.messagesDesc': 'تواصل مع الإدارة أو الأعضاء الآخرين.',
    'portal.team': 'الفريق',
    'portal.teamDesc': 'تعرّف على من يدعم نداء السلام.',
    'portal.settings': 'الإعدادات',
    'portal.settingsDesc': 'أدر ملفك الشخصي وحسابك.',
    'portal.admin': 'لوحة الإدارة',
    'portal.adminDesc': 'إدارة المحتوى والمنشورات والإعدادات.',
    'portal.openChat': 'فتح الدردشة',
    'portal.goto': 'انتقال',
    'portal.open': 'فتح',
    'portal.manage': 'إدارة',
    // Admins
    'admins.team': 'فريق المشروع',
    'admins.teamDesc': 'تعرّف على من يقف وراء نداء السلام.',
    'admins.founder': 'المؤسس',
    'admins.admin': 'مشرف',
    'admins.writeMessage': 'إرسال رسالة',
    // Admin panel
    'admin.panel': 'لوحة الإدارة',
    'admin.signInRequired': 'يرجى تسجيل الدخول للمتابعة.',
    'admin.signIn': 'تسجيل الدخول',
    'admin.accessDenied': 'الوصول مرفوض',
    'admin.accessDeniedDesc': 'حسابك غير مسجّل كمشرف. تواصل مع صاحب الموقع.',
    'admin.signOut': 'تسجيل الخروج',
    'admin.content': 'المحتوى',
    'admin.posts': 'المنشورات',
    'admin.messages': 'الرسائل',
    'admin.admins': 'المشرفون',
    'admin.users': 'المستخدمون',
    'admin.newPost': 'منشور جديد',
    'admin.transferOwner': 'نقل الملكية',
    'admin.makeAdmin': 'تعيين كمشرف',
    'admin.save': 'حفظ',
    'admin.cancel': 'إلغاء',
    'admin.delete': 'حذف',
    'admin.edit': 'تعديل',
    'admin.back': 'رجوع',
    'admin.published': 'منشور',
    'admin.draft': 'مسودة',
    'admin.title': 'العنوان',
    'admin.excerpt': 'مقتطف',
    'admin.coverUrl': 'رابط صورة الغلاف',
    'admin.content_text': 'المحتوى',
    'admin.attachments': 'المرفقات',
    'admin.addFiles': 'إضافة ملفات',
    'admin.uploading': 'جارٍ الرفع...',
    'post.attachments': 'المرفقات',
    'post.download': 'تنزيل',
    'admin.addNew': 'إضافة',
    'admin.noItems': 'لا توجد عناصر بعد',
    'admin.inbox': 'صندوق الوارد',
    'admin.noMessages': 'لا توجد رسائل بعد',
    'admin.selectMsg': 'اختر رسالة للعرض',
    'admin.reply': 'رد',
    'admin.replyPlaceholder': 'اكتب رداً...',
    'admin.sendReply': 'إرسال الرد',
    'admin.noSubject': 'بلا موضوع',
    'admin.from': 'من',
    'admin.youOwner': 'أنت المشرف الرئيسي.',
    'admin.ownerDesc': 'يمكنك تعيين مستخدمين آخرين كمشرفين ونقل الملكية.',
    'admin.inviteAdmin': 'إضافة مشرف',
    'admin.inviteEmail': 'بريد المستخدم',
    'admin.inviteRole': 'الدور',
    'admin.roleEditor': 'محرر',
    'admin.roleOwner': 'مالك',
    'admin.invite': 'إضافة',
    'admin.banUser': 'حظر',
    'admin.unbanUser': 'رفع الحظر',
    'admin.muteUser': 'كتم',
    'admin.unmuteUser': 'رفع الكتم',
    'admin.deleteUser': 'حذف المستخدم',
    'admin.banned': 'محظور',
    'admin.muted': 'مكتوم',
    'admin.active': 'نشط',
    'admin.noUsers': 'لا يوجد مستخدمون',
    'admin.userMgmt': 'إدارة المستخدمين',
    'admin.userMgmtDesc': 'حظر وكتم وحذف المستخدمين',
    'admin.confirmBan': 'هل تريد حظر هذا المستخدم؟',
    'admin.confirmDelete': 'هل تريد حذف هذا المستخدم؟ لا يمكن التراجع.',
    'admin.fieldKey': 'الحقل',
    'admin.fieldValue': 'القيمة',
    'admin.fieldGroup': 'المجموعة',
    'admin.fieldType': 'النوع',
    'admin.contentMgmt': 'إدارة المحتوى',
    'admin.contentDesc': 'تعديل النصوص والصور والروابط على الموقع',
    // Messages
    'messages.title': 'الرسائل',
    'messages.subtitle': 'محادثاتك مع الفريق وأعضاء المجتمع',
    'messages.newConv': 'محادثة جديدة',
    'messages.noConvs': 'لا توجد محادثات نشطة بعد',
    'messages.search': 'بحث في المحادثات...',
    'messages.admin': 'الإدارة',
    'messages.noMessages': 'لا توجد رسائل',
    'messages.selectConv': 'اختر محادثة للبدء',
    'messages.send': 'إرسال',
    'messages.type': 'اكتب رسالة...',
    'messages.newDialog': 'بدء حوار',
    'messages.support': 'الدعم / الإدارة',
    'messages.supportDesc': 'اطرح سؤالاً على فريق الموقع',
    'messages.or': 'أو مع عضو',
    'messages.searchUser': 'البحث بالاسم...',
    'messages.noUsers': 'لم يتم العثور على مستخدمين',
    // Hadiths
    'nav.hadiths': 'الأحاديث',
    'hadiths.title': 'الأحاديث',
    'hadiths.subtitle': 'أقوال النبي ﷺ مع درجة صحتها',
    'hadiths.all': 'الكل',
    'hadiths.none': 'لا توجد أحاديث بعد.',
    'hadiths.narrator': 'الراوي',
    'hadiths.source': 'المصدر',
    'admin.hadiths': 'الأحاديث',
    'admin.newHadith': 'حديث جديد',
    'admin.hadithText': 'نص الحديث',
    'admin.hadithSource': 'المصدر (الكتاب، الرقم)',
    'admin.hadithNarrator': 'الراوي',
    'admin.hadithTopic': 'الموضوع',
    'admin.hadithGrade': 'درجة الصحة',
    'admin.gradeSahih': 'صحيح',
    'admin.gradeHasan': 'حسن',
    'admin.gradeDaif': 'ضعيف',
    'admin.gradeMawdu': 'موضوع',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved && ['RU', 'EN', 'AR'].includes(saved) ? saved : 'RU';
  });

  const isRtl = language === 'AR';

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    document.documentElement.dir = isRtl ? 'rtl' : 'ltr';
    document.documentElement.lang = language.toLowerCase();
  }, [isRtl, language]);

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations['EN']?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
